### ISSUE TITLE
Set up auto-deploy from GitHub for Heroku

### ISSUE THREAD

**Issue by kevinji** [calhacks/website2#6]
If you connect your Heroku account to GitHub under the "Deploy" section you can have Heroku automatically deploy whenever a new commit pushes to master. No more dealing with Heroku's separate Git repo!

**Comment by Zhipan1** [comment]
Want to keep development (github) separate from production(heroku). Pushing to heroku is one line in terminal so it's not a big deal :)

**Comment by Zhipan1** [comment]
On second thought, it lets people make live changes without having heroku push access (removes me as a bottleneck). Great idea! Enabled auto deploy :)
